run-name: ${{ github.actor }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Otto test
    steps:
      - name: Checking the source code
        uses: actions/checkout@v4
      - name: Setup wrangler
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'
          check-latest: true
          architecture: 'x64'
          cache-dependency-path: ../../yarn.lock
      - run: |
          yarn --frozen-lockfile
          yarn test


  deploy:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
      - name: Deploying Otto
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          path: ../../
          command: deploy
      # - run: yarn deploy
