run-name: ${{ github.actor }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Otto test
    steps:
      - uses: actions/setup-node@v4
      - name: Setup wrangler
        with:
          node-version: '23.9'
          check-latest: true
          architecture: 'x64'
        working-directory: ./CF-OttoBack
        run: |
          yarn
          pwd
          yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: cloudlare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: production
          wranglerVersion: "3.114.0"
          packageManager: yarn
          command: yarn deploy
