run-name: ${{ github.actor }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Otto test
    steps:
      - name: Setup wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          node-version: '23.x'
          check-latest: true
          architecture: 'x64'
      - run: yarn
      - run: yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: cloudlare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: production
          wranglerVersion: "3.114.0"
          packageManager: yarn
          command: yarn deploy
