name: Otto-CDCI
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Otto-CDCI
    strategy:
      fail-fast: false
      matrix:
        node-version: ['18.x', '23.x']

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@4
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn --frozen-lockfile


  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: cloudlare/wrangler-action@v3
      - name: deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: production
          wranglerVersion: "3.114.0"
          packageManager: yarn
          command: yarn deploy
