run-name: ${{ github.actor }}

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Otto test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@3
        with:
          node-version: '20'
          packageManager: yarn
          check-latest: true
          architecture: 'x64'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn test


  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: cloudlare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: production
          wranglerVersion: "3.114.0"
          packageManager: yarn
          command: yarn deploy
