name: Otto-CDCI
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Otto-CDCI
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@4
        with:
          packageManager: yarn
          node-version: '23.x'
      - run: yarn
      - run: yarn --frozen-lockfile


  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: cloudlare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: production
          wranglerVersion: "3.114.0"
          packageManager: yarn
          command: yarn deploy
